version: '2'
services:
    imdock-nginx:
      restart: always
#      image: nginx
      image: jboesl/docker-nginx-headers-more
      container_name: nginx-4000port
      volumes:
          - "./config:/etc/nginx/conf.d"
         # - "./config/80port.conf:/etc/nginx/conf.d/80port.conf"
          - "./config/sites-module:/etc/nginx/sites-module"
          - "./public_html:/var/www/html"
      ports:
          - "4000:80"
         # - "443:443"
      command: [nginx-debug, '-g', 'daemon off;']



networks:
    default:
        external:
            name: imdockgroup
