version: '2'
services:
    imdock-nginx:
      restart: always
      image: nginx
#      image: jboesl/docker-nginx-headers-more
      container_name: imdock-nginx
      volumes:
          - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
          - "./etc/nginx/sites-module:/etc/nginx/sites-module"
          - "./src:/var/www/html"
      ports:
          - "80:80"
      command: [nginx-debug, '-g', 'daemon off;']



networks:
    default:
        external:
            name: imdockgroup