version: '2'
services:
    imdock-nginx:
      restart: always
#      image: nginx
      image: jboesl/docker-nginx-headers-more
      container_name: imdock-nginx
      volumes:
           - "./etc/nginx:/etc/nginx/conf.d"
         # - "./etc/nginx/80port.conf:/etc/nginx/conf.d/80port.conf"
         # - "./etc/nginx/sites-module:/etc/nginx/sites-module"
          - "./public_html:/var/www/html"
      ports:
          - "80:80"
      command: [nginx-debug, '-g', 'daemon off;']



networks:
    default:
        external:
            name: imdockgroup
