version: '2'
services:
    imdock-nginx:
      restart: always
      image: nginx
      container_name: imdock-nginx
      volumes:
          - "./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
          - "./src:/var/www/html"
      ports:
          - "81:80"
      command: [nginx-debug, '-g', 'daemon off;']



networks:
    default:
        external:
            name: imdockgroup